2018-07-06 14:43:04,440,12528,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:43:04,518,12528,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:43:04,698,12528,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:43:07,106,12528,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:43:07,151,12528,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:43:07,196,12528,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:43:07,274,12528,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:43:07,311,12528,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:46:33,878,1148,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:46:33,996,1148,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:46:34,178,1148,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:46:36,594,1148,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:46:36,643,1148,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:46:36,686,1148,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:46:36,772,1148,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:46:36,810,1148,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:47:05,248,15168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:47:05,347,15168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:47:05,845,15168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:47:07,068,15168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:47:07,105,15168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:47:07,179,15168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:47:07,222,15168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:47:07,253,15168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 86, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:48:30,284,3808,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:48:30,345,3808,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:48:30,501,3808,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:48:33,326,3808,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:48:33,366,3808,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:48:33,439,3808,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:48:33,470,3808,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:48:33,511,3808,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:06,221,11220,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:06,289,11220,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:06,798,11220,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:09,818,11220,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:09,859,11220,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:09,946,11220,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:09,989,11220,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:10,039,11220,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:25,641,3644,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:25,744,3644,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:26,287,3644,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:28,998,3644,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:29,048,3644,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:29,132,3644,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:29,171,3644,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:29,205,3644,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:46,862,6752,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:46,943,6752,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:47,461,6752,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:49,829,6752,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:49,871,6752,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:49,952,6752,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:50,001,6752,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:49:50,056,6752,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:09,354,14720,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:09,441,14720,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:09,982,14720,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:13,276,14720,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:13,318,14720,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:13,397,14720,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:13,448,14720,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:13,496,14720,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:44,365,12464,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:44,438,12464,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:44,605,12464,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:47,688,12464,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:47,727,12464,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:47,802,12464,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:47,844,12464,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:50:47,884,12464,root,ERROR,auto_task_test.py:92,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:52:57,034,1656,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:52:57,248,1656,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:52:57,556,1656,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:00,862,1656,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:00,940,1656,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:01,092,1656,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:01,130,1656,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:01,167,1656,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:48,433,6092,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:48,901,6092,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:49,880,6092,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:52,817,6092,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:52,857,6092,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:52,931,6092,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:52,968,6092,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:53:53,008,6092,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:58:06,860,10788,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:58:07,322,10788,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:58:08,315,10788,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:58:10,893,10788,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:58:10,949,10788,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:58:11,039,10788,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:58:11,078,10788,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:58:11,112,10788,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:59:14,215,10168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:59:14,672,10168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:59:15,965,10168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:59:19,295,10168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:59:19,393,10168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:59:19,428,10168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:59:19,475,10168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 14:59:19,522,10168,root,ERROR,auto_task_test.py:94,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:27,463,5948,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:27,615,5948,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:29,249,5948,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:31,839,5948,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:31,922,5948,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:31,969,5948,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:32,016,5948,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:32,078,5948,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:44,360,1416,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:44,482,1416,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:44,920,1416,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:48,230,1416,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:48,346,1416,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:48,403,1416,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:48,452,1416,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:01:48,501,1416,root,ERROR,auto_task_test.py:95,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 85, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:02:50,441,6884,root,ERROR,auto_task_test.py:98,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 88, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:02:50,853,6884,root,ERROR,auto_task_test.py:98,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 88, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:02:51,729,6884,root,ERROR,auto_task_test.py:98,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 88, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:02:55,296,6884,root,ERROR,auto_task_test.py:98,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 88, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:02:55,377,6884,root,ERROR,auto_task_test.py:98,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 88, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:02:55,422,6884,root,ERROR,auto_task_test.py:98,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 88, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:02:55,462,6884,root,ERROR,auto_task_test.py:98,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 88, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:02:55,507,6884,root,ERROR,auto_task_test.py:98,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 88, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:04:21,331,13108,root,ERROR,auto_task_test.py:99,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 89, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:04:21,803,13108,root,ERROR,auto_task_test.py:99,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 89, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:04:22,752,13108,root,ERROR,auto_task_test.py:99,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 89, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:04:26,112,13108,root,ERROR,auto_task_test.py:99,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 89, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:04:26,251,13108,root,ERROR,auto_task_test.py:99,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 89, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:04:26,314,13108,root,ERROR,auto_task_test.py:99,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 89, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:04:26,428,13108,root,ERROR,auto_task_test.py:99,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 89, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:04:26,497,13108,root,ERROR,auto_task_test.py:99,list index out of range
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 89, in test_api
    param_data = re.findall(pattern[0], param_data.replace("\'", "\""))[0]
IndexError: list index out of range
2018-07-06 15:10:34,307,6620,root,ERROR,auto_task_test.py:97,Negative indexing is not supported.
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    AutomationCaseTestResult.objects.filter(automationCaseApi=api_id[0])[-1]))[0]['fields']["responseData"]
  File "D:\Program Files (x86)\python\lib\site-packages\django\db\models\query.py", line 286, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2018-07-06 15:10:34,936,6620,root,ERROR,auto_task_test.py:97,Negative indexing is not supported.
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    AutomationCaseTestResult.objects.filter(automationCaseApi=api_id[0])[-1]))[0]['fields']["responseData"]
  File "D:\Program Files (x86)\python\lib\site-packages\django\db\models\query.py", line 286, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2018-07-06 15:10:35,912,6620,root,ERROR,auto_task_test.py:97,Negative indexing is not supported.
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    AutomationCaseTestResult.objects.filter(automationCaseApi=api_id[0])[-1]))[0]['fields']["responseData"]
  File "D:\Program Files (x86)\python\lib\site-packages\django\db\models\query.py", line 286, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2018-07-06 15:10:39,148,6620,root,ERROR,auto_task_test.py:97,Negative indexing is not supported.
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    AutomationCaseTestResult.objects.filter(automationCaseApi=api_id[0])[-1]))[0]['fields']["responseData"]
  File "D:\Program Files (x86)\python\lib\site-packages\django\db\models\query.py", line 286, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2018-07-06 15:10:39,180,6620,root,ERROR,auto_task_test.py:97,Negative indexing is not supported.
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    AutomationCaseTestResult.objects.filter(automationCaseApi=api_id[0])[-1]))[0]['fields']["responseData"]
  File "D:\Program Files (x86)\python\lib\site-packages\django\db\models\query.py", line 286, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2018-07-06 15:10:39,215,6620,root,ERROR,auto_task_test.py:97,Negative indexing is not supported.
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    AutomationCaseTestResult.objects.filter(automationCaseApi=api_id[0])[-1]))[0]['fields']["responseData"]
  File "D:\Program Files (x86)\python\lib\site-packages\django\db\models\query.py", line 286, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2018-07-06 15:10:39,286,6620,root,ERROR,auto_task_test.py:97,Negative indexing is not supported.
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    AutomationCaseTestResult.objects.filter(automationCaseApi=api_id[0])[-1]))[0]['fields']["responseData"]
  File "D:\Program Files (x86)\python\lib\site-packages\django\db\models\query.py", line 286, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2018-07-06 15:10:39,316,6620,root,ERROR,auto_task_test.py:97,Negative indexing is not supported.
Traceback (most recent call last):
  File "E:\project\api_automation_test\api_test\common\auto_task_test.py", line 84, in test_api
    AutomationCaseTestResult.objects.filter(automationCaseApi=api_id[0])[-1]))[0]['fields']["responseData"]
  File "D:\Program Files (x86)\python\lib\site-packages\django\db\models\query.py", line 286, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
